apiVersion: v1
kind: Service
metadata:
  name: ai-gateway
  labels:
    app: ai-gateway
spec:
  type: ClusterIP
  selector:
    app: ai-gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP